### ISSUE TITLE
TwilioVoice fails to configure

### ISSUE THREAD

**Issue by tyoungNIO** [nio-blocks/twilio#22]
```[2018-05-18 15:39:25.987] NIO [ERROR] [twilio.96161c12-123b-4eda-8fb0-e3626a9eed3f] Failed to configure
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nio\util\runner.py", line 79, in do_c
onfigure
    self.configure(context)
  File "C:\Users\Tom\nio\projects\nio3\blocks\twilio\voice_block.py", line 70, in configure
    self.configure_server(conf, Speak(self.endpoint(), self))
AttributeError: 'TwilioVoice' object has no attribute 'configure_server'```

**Comment by tyoungNIO** [comment]
fixed in #23
